/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/
import { TypedClientGenerator } from '../src/generators/TypedClientGenerator';
import { ControllerInfo } from '../src/scanner/ScannerService';

// ─── Shared fixtures ──────────────────────────────────────────────────────────

const makeController = (overrides: Partial<ControllerInfo> = {}): ControllerInfo => ({
  name: 'UsersController',
  path: 'users',
  methods: [],
  ...overrides,
});

const stringType = { type: 'string', isArray: false, isOptional: false };
const numberType = { type: 'number', isArray: false, isOptional: false };
const optionalNumberType = { type: 'number', isArray: false, isOptional: true };
const userDtoType = { type: 'UserDto', isArray: false, isOptional: false };
const userArrayType = { type: 'UserDto', isArray: true, isOptional: false };

/** A DTO whose shape the analyzer was able to resolve from the AST. */
const resolvedUserDtoType = {
  type: 'UserDto',
  isArray: false,
  isOptional: false,
  properties: [
    { name: 'id', type: numberType },
    { name: 'email', type: stringType },
  ],
};

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('TypedClientGenerator', () => {
  let gen: TypedClientGenerator;

  beforeEach(() => {
    gen = new TypedClientGenerator('http://localhost:3000');
  });

  // ── Header ────────────────────────────────────────────────────────────────

  describe('file header', () => {
    it('emits the auto-generated comment', () => {
      const out = gen.generate([makeController()], '1.2.3');
      expect(out).toContain('Auto-generated by specscribe v1.2.3');
    });

    it('stamps the real package version when none is given', () => {
      // A hard-coded default would stamp a stale version into files the user trusts.
      const { version } = require('../package.json');
      const out = gen.generate([makeController()]);

      expect(out).toContain(`Auto-generated by specscribe v${version}`);
      expect(out).not.toContain('v1.2.3');
    });

    it('emits the re-generate hint', () => {
      const out = gen.generate([makeController()]);
      expect(out).toContain('npx specscribe generate src --format client');
    });
  });

  // ── DTO types ──────────────────────────────────────────────────────────

  describe('DTO types', () => {
    it('emits a real interface when the DTO shape is resolved', () => {
      const controller = makeController({
        methods: [
          {
            name: 'getUser',
            httpMethod: 'GET',
            route: ':id',
            parameters: [{ name: 'id', type: stringType, decorator: 'Param', parameterLocation: 'path' }],
            returnType: resolvedUserDtoType,
          },
        ],
      });
      const out = gen.generate([controller]);
      expect(out).toContain('export interface UserDto {');
      expect(out).toMatch(/id:\s*number;/);
      expect(out).toMatch(/email:\s*string;/);
    });

    it('never emits an index-signature stub, which would defeat type safety', () => {
      const controller = makeController({
        methods: [
          {
            name: 'getUser',
            httpMethod: 'GET',
            route: ':id',
            parameters: [],
            returnType: resolvedUserDtoType,
          },
        ],
      });
      expect(gen.generate([controller])).not.toContain('[key: string]: unknown');
    });

    it('emits an unknown alias when the shape cannot be resolved from the AST', () => {
      // Happens when a controller method has no explicit return type, so the
      // analyzer never sees the property list. Surfacing `unknown` makes the
      // missing information visible instead of silently accepting anything.
      const controller = makeController({
        methods: [
          {
            name: 'getUser',
            httpMethod: 'GET',
            route: ':id',
            parameters: [],
            returnType: userDtoType,
          },
        ],
      });
      const out = gen.generate([controller]);
      expect(out).toContain('export type UserDto = unknown;');
    });

    it('does not emit primitive types as stubs', () => {
      const controller = makeController({
        methods: [
          {
            name: 'ping',
            httpMethod: 'GET',
            route: 'ping',
            parameters: [],
            returnType: stringType,
          },
        ],
      });
      const out = gen.generate([controller]);
      expect(out).not.toContain('export interface string');
      expect(out).not.toContain('export interface number');
    });

    it('declares each DTO exactly once even when referenced repeatedly', () => {
      const controller = makeController({
        methods: [
          {
            name: 'getOne',
            httpMethod: 'GET',
            route: ':id',
            parameters: [],
            returnType: resolvedUserDtoType,
          },
          {
            name: 'getAll',
            httpMethod: 'GET',
            route: '',
            parameters: [],
            returnType: { ...resolvedUserDtoType, isArray: true },
          },
        ],
      });
      const out = gen.generate([controller]);
      const matches = (out.match(/export interface UserDto\b/g) || []).length;
      expect(matches).toBe(1);
    });

    it('emits enum-typed properties as string literal unions', () => {
      const controller = makeController({
        methods: [
          {
            name: 'getOne',
            httpMethod: 'GET',
            route: ':id',
            parameters: [],
            returnType: {
              type: 'AccountDto',
              isArray: false,
              isOptional: false,
              properties: [
                {
                  name: 'status',
                  type: {
                    type: 'AccountStatus',
                    isArray: false,
                    isOptional: false,
                    enumValues: ['active', 'suspended'],
                  },
                },
              ],
            },
          },
        ],
      });
      const out = gen.generate([controller]);
      expect(out).toContain("export type AccountStatus = 'active' | 'suspended';");
      expect(out).toMatch(/status:\s*AccountStatus;/);
    });
  });

  // ── Class generation ───────────────────────────────────────────────────────

  describe('controller class', () => {
    it('generates a class named <Controller>Client', () => {
      const out = gen.generate([makeController({
        methods: [{ name: 'find', httpMethod: 'GET', route: '', parameters: [], returnType: stringType }],
      })]);
      expect(out).toContain('export class UsersControllerClient');
    });

    it('skips controllers with no methods', () => {
      const out = gen.generate([makeController({ methods: [] })]);
      expect(out).not.toContain('export class');
    });

    it('generates a constructor accepting baseUrl', () => {
      const controller = makeController({
        methods: [{ name: 'getAll', httpMethod: 'GET', route: '', parameters: [], returnType: stringType }],
      });
      const out = gen.generate([controller]);
      expect(out).toContain("constructor(private readonly baseUrl: string)");
    });
  });

  // ── GET method — no params ─────────────────────────────────────────────────

  describe('GET method with no params', () => {
    const controller = makeController({
      methods: [{ name: 'findAll', httpMethod: 'GET', route: '', parameters: [], returnType: userArrayType }],
    });

    it('generates an async method', () => {
      const out = gen.generate([controller]);
      expect(out).toContain('async findAll()');
    });

    it('uses native fetch without method option for GET', () => {
      const out = gen.generate([controller]);
      expect(out).toMatch(/fetch\(`\$\{this\.baseUrl\}\/users`\)/);
    });

    it('returns the correct type', () => {
      const out = gen.generate([controller]);
      expect(out).toContain('Promise<UserDto[]>');
    });

    it('throws on non-ok response', () => {
      const out = gen.generate([controller]);
      expect(out).toContain("throw new Error");
    });
  });

  // ── GET method — path param ────────────────────────────────────────────────

  describe('GET method with path param', () => {
    const controller = makeController({
      methods: [
        {
          name: 'findOne',
          httpMethod: 'GET',
          route: ':id',
          parameters: [{ name: 'id', type: numberType, decorator: 'Param', parameterLocation: 'path' }],
          returnType: userDtoType,
        },
      ],
    });

    it('includes the path param in the function signature', () => {
      const out = gen.generate([controller]);
      expect(out).toContain('id: number');
    });

    it('interpolates the path param into the URL', () => {
      const out = gen.generate([controller]);
      expect(out).toContain('${id}');
    });

    it('does NOT produce $${id} (regression: double-replace bug)', () => {
      const out = gen.generate([controller]);
      // The bug caused :id → ${id} correctly, then {id} inside ${id} was
      // replaced again, producing $${id}. Ensure this never regresses.
      expect(out).not.toContain('$${id}');
    });

    it('handles {param} style route as well as :param style', () => {
      const curlyController = makeController({
        methods: [{
          name: 'findOne',
          httpMethod: 'GET',
          route: '{id}',
          parameters: [{ name: 'id', type: numberType, decorator: 'Param', parameterLocation: 'path' }],
          returnType: userDtoType,
        }],
      });
      const out = gen.generate([curlyController]);
      expect(out).toContain('${id}');
      expect(out).not.toContain('$${id}');
    });
  });

  // ── GET method — query params ──────────────────────────────────────────────

  describe('GET method with query params', () => {
    const controller = makeController({
      methods: [
        {
          name: 'search',
          httpMethod: 'GET',
          route: 'search',
          parameters: [
            { name: 'q', type: stringType, decorator: 'Query', parameterLocation: 'query' },
            { name: 'limit', type: optionalNumberType, decorator: 'Query', parameterLocation: 'query' },
          ],
          returnType: userArrayType,
        },
      ],
    });

    it('uses URL and searchParams for query params', () => {
      const out = gen.generate([controller]);
      expect(out).toContain('new URL(');
      expect(out).toContain('searchParams.set');
    });

    it('wraps optional query param in an undefined check', () => {
      const out = gen.generate([controller]);
      expect(out).toContain("if (limit !== undefined)");
    });

    it('does NOT wrap required query param in an undefined check', () => {
      const out = gen.generate([controller]);
      expect(out).not.toContain("if (q !== undefined)");
    });
  });

  // ── POST / body param ─────────────────────────────────────────────────────

  describe('POST method with body', () => {
    const controller = makeController({
      methods: [
        {
          name: 'create',
          httpMethod: 'POST',
          route: '',
          parameters: [{ name: 'dto', type: userDtoType, decorator: 'Body', parameterLocation: 'body' }],
          returnType: userDtoType,
        },
      ],
    });

    it('sets method: POST in fetch options', () => {
      const out = gen.generate([controller]);
      expect(out).toContain("method: 'POST'");
    });

    it('sets Content-Type header', () => {
      const out = gen.generate([controller]);
      expect(out).toContain("'Content-Type': 'application/json'");
    });

    it('JSON.stringifies the body param', () => {
      const out = gen.generate([controller]);
      expect(out).toContain('JSON.stringify(dto)');
    });
  });

  // ── DELETE method ─────────────────────────────────────────────────────────

  describe('DELETE method', () => {
    const controller = makeController({
      methods: [
        {
          name: 'remove',
          httpMethod: 'DELETE',
          route: ':id',
          parameters: [{ name: 'id', type: stringType, decorator: 'Param', parameterLocation: 'path' }],
          returnType: { type: 'void', isArray: false, isOptional: false },
        },
      ],
    });

    it('sets method: DELETE', () => {
      const out = gen.generate([controller]);
      expect(out).toContain("method: 'DELETE'");
    });

    it('does not call res.json() for void return type', () => {
      const out = gen.generate([controller]);
      // The method should not contain return _res.json() since return is void
      expect(out).not.toContain('return _res.json()');
    });
  });

  // ── Aggregate ApiClient ───────────────────────────────────────────────────

  describe('aggregate ApiClient', () => {
    it('generates an ApiClient class', () => {
      const controller = makeController({
        methods: [{ name: 'findAll', httpMethod: 'GET', route: '', parameters: [], returnType: stringType }],
      });
      const out = gen.generate([controller]);
      expect(out).toContain('export class ApiClient');
    });

    it('exposes each controller as a property', () => {
      const controller = makeController({
        methods: [{ name: 'findAll', httpMethod: 'GET', route: '', parameters: [], returnType: stringType }],
      });
      const out = gen.generate([controller]);
      // Property name is camelCase of controller name minus "Controller"
      expect(out).toContain('users:');
    });

    it('instantiates each sub-client with baseUrl in the constructor', () => {
      const controller = makeController({
        methods: [{ name: 'findAll', httpMethod: 'GET', route: '', parameters: [], returnType: stringType }],
      });
      const out = gen.generate([controller]);
      expect(out).toContain('new UsersControllerClient(baseUrl)');
    });

    it('does not add empty controllers to ApiClient', () => {
      const out = gen.generate([makeController({ methods: [] })]);
      expect(out).not.toContain('export class ApiClient');
    });
  });

  describe('global prefix', () => {
    it('prepends the global prefix to generated URLs', () => {
      const prefixed = new TypedClientGenerator('http://localhost:3000', 'api');
      const controller = makeController({
        methods: [{ name: 'findAll', httpMethod: 'GET', route: '', parameters: [], returnType: stringType }],
      });
      const out = prefixed.generate([controller]);
      expect(out).toContain("fetch(`${this.baseUrl}/api/users`)");
    });
  });
});
