sonar.projectKey=Eng-MMustafa_specscribe
sonar.organization=m7trfnet0
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.exclusions=src/examples/**,src/controllers/DemoController.ts,dist/**,node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
