/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/

/**
 * Generates a Dart client from an OpenAPI document.
 *
 * Output depends on `dart:convert` and `package:http/http.dart`. Component
 * schemas become Dart classes with `fromJson`/`toJson`; paths become methods on
 * `ApiClient`.
 */
export class DartClientGenerator {
  private baseUrl: string;
  private schemas: Record<string, any> = {};
  private generatedTypes = new Set<string>();

  constructor(baseUrl = 'http://localhost:3000') {
    this.baseUrl = baseUrl.replace(/\/$/, '');
  }

  generate(spec: any): string {
    this.schemas = spec.components?.schemas || {};
    this.generatedTypes.clear();

    const lines: string[] = [];
    lines.push('// Auto-generated by specscribe — do not edit manually');
    lines.push('// Re-generate: npx specscribe generate src --format dart-client');
    lines.push("import 'dart:convert';");
    lines.push("import 'package:http/http.dart' as http;");
    lines.push('');

    const schemaNames = Object.keys(this.schemas).sort();
    if (schemaNames.length > 0) {
      lines.push('// ─── Models ──────────────────────────────────────────────────────────');
      for (const name of schemaNames) {
        lines.push(this.classForSchema(name, this.schemas[name]));
      }
      lines.push('');
    }

    lines.push('// ─── Client ──────────────────────────────────────────────────────────');
    lines.push('class ApiClient {');
    lines.push(`  final String baseUrl = "${this.baseUrl}";`);
    lines.push('  final http.Client _client = http.Client();');
    lines.push('');

    const operations = this.collectOperations(spec.paths || {});
    for (const op of operations) {
      lines.push(this.methodForOperation(op).map(l => `  ${l}`).join('\n'));
      lines.push('');
    }
    lines.push('}');

    return lines.join('\n') + '\n';
  }

  private classForSchema(name: string, schema: any, visited = new Set<string>()): string {
    if (this.generatedTypes.has(name)) return '';
    this.generatedTypes.add(name);

    if (visited.has(name)) {
      return `class ${name} {\n  ${name}();\n}`;
    }
    visited.add(name);

    const properties = schema.properties || {};
    const required = new Set(schema.required || []);
    const lines: string[] = [];

    for (const propSchema of Object.values(properties) as any[]) {
      if (propSchema.type === 'object' && propSchema.properties && propSchema.title && !this.generatedTypes.has(propSchema.title)) {
        lines.push(this.classForSchema(propSchema.title, propSchema, visited));
      }
    }

    lines.push(`class ${name} {`);
    const propKeys = Object.keys(properties);
    for (const propName of propKeys) {
      const propSchema = properties[propName];
      const dartType = this.schemaToDartType(propSchema, !required.has(propName));
      lines.push(`  final ${dartType} ${this.safeDartName(propName)};`);
    }

    lines.push('');
    lines.push(`  ${name}({`);
    for (const propName of propKeys) {
      lines.push(`    ${!required.has(propName) ? '' : 'required '}this.${this.safeDartName(propName)},`);
    }
    lines.push('  });');

    lines.push('');
    lines.push(`  factory ${name}.fromJson(Map<String, dynamic> json) {`);
    lines.push(`    return ${name}(`);
    for (const propName of propKeys) {
      const propSchema = properties[propName];
      const field = this.safeDartName(propName);
      lines.push(`      ${field}: ${this.fromJsonExpression(propSchema, `json["${propName}"]`)},`);
    }
    lines.push('    );');
    lines.push('  }');

    lines.push('');
    lines.push('  Map<String, dynamic> toJson() => {');
    for (const propName of propKeys) {
      const field = this.safeDartName(propName);
      lines.push(`    "${propName}": ${this.toJsonExpression(properties[propName], field)},`);
    }
    lines.push('  };');
    lines.push('}');

    visited.delete(name);
    return lines.filter(Boolean).join('\n');
  }

  private methodForOperation(op: Operation): string[] {
    const { path, method, operation } = op;
    const methodName = this.methodName(operation.operationId, method, path);
    const params = this.extractParameters(operation);
    const bodyParam = operation.requestBody?.content?.['application/json'];

    const sigParts: string[] = [];
    for (const p of params) {
      const dartType = this.schemaToDartType(p.schema, !p.required);
      sigParts.push(`${dartType} ${this.safeDartName(p.name)}`);
    }
    if (bodyParam?.schema) {
      sigParts.push(`${this.schemaToDartType(bodyParam.schema, false)} body`);
    }

    const lines: string[] = [];
    lines.push(`Future<http.Response> ${methodName}(${sigParts.length ? `{${sigParts.join(', ')}}` : ''}) async {`);

    let urlPath = path;
    for (const p of params.filter(x => x.in === 'path')) {
      urlPath = urlPath.replace(`{${p.name}}`, `$${this.safeDartName(p.name)}`);
    }
    lines.push(`    final url = Uri.parse("${this.baseUrl}${urlPath}");`);

    const queryParams = params.filter(x => x.in === 'query');
    const httpMethod = method.toLowerCase();
    const bodyArg = bodyParam ? ', headers: {"Content-Type": "application/json"}, body: jsonEncode(body.toJson())' : '';
    if (queryParams.length > 0) {
      lines.push('    final query = <String, String>{};');
      for (const q of queryParams) {
        lines.push(`    if (${this.safeDartName(q.name)} != null) query["${q.name}"] = ${this.safeDartName(q.name)}.toString();`);
      }
      lines.push(`    final response = await _client.${httpMethod}(url.replace(queryParameters: query)${bodyArg});`);
    } else {
      lines.push(`    final response = await _client.${httpMethod}(url${bodyArg});`);
    }
    lines.push('    return response;');
    lines.push('  }');

    return lines;
  }

  private extractParameters(operation: any): Parameter[] {
    return (operation.parameters || []).map((p: any) => ({
      name: p.name,
      in: p.in,
      required: p.required === true,
      schema: p.schema || {},
    }));
  }

  private collectOperations(paths: Record<string, Record<string, any>>): Operation[] {
    const operations: Operation[] = [];
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (typeof operation !== 'object' || !operation) continue;
        operations.push({ path, method: method.toLowerCase(), operation });
      }
    }
    return operations;
  }

  private schemaToDartType(schema: any, optional: boolean): string {
    if (!schema) return 'dynamic';
    if (schema.$ref) {
      const name = schema.$ref.split('/').pop();
      return optional ? `${name}?` : name;
    }
    if (Array.isArray(schema.type)) {
      return optional ? 'dynamic?' : 'dynamic';
    }
    if (schema.type === 'array') {
      const item = this.schemaToDartType(schema.items, false);
      return optional ? `List<${item}>?` : `List<${item}>`;
    }
    if (schema.enum) return optional ? 'String?' : 'String';
    let type: string;
    switch (schema.type) {
      case 'string':
        type = schema.format === 'date-time' ? 'DateTime' : 'String';
        break;
      case 'integer':
      case 'number': type = 'num'; break;
      case 'boolean': type = 'bool'; break;
      case 'object':
        type = schema.title ? schema.title : 'Map<String, dynamic>';
        break;
      default:
        type = 'dynamic';
    }
    return optional ? `${type}?` : type;
  }

  private fromJsonExpression(schema: any, expr: string): string {
    if (schema.$ref) {
      const name = schema.$ref.split('/').pop();
      return `${name}.fromJson(${expr})`;
    }
    if (schema.type === 'array' && schema.items) {
      const item = this.schemaToDartType(schema.items, false);
      return `(${expr} as List).map((e) => ${item === 'Map<String, dynamic>' ? 'e as Map<String, dynamic>' : this.fromJsonExpression(schema.items, 'e')}).toList()`;
    }
    return expr;
  }

  private toJsonExpression(schema: any, field: string): string {
    if (schema.$ref) {
      return `${field}.toJson()`;
    }
    if (schema.type === 'array' && schema.items?.$ref) {
      return `${field}.map((e) => e.toJson()).toList()`;
    }
    return field;
  }

  private methodName(operationId: string | undefined, method: string, path: string): string {
    if (operationId) return this.safeDartName(operationId);
    const parts = path.replace(/[{}]/g, '').split('/').filter(Boolean);
    const name = parts.length === 0 ? 'Root' : parts.map(p => p[0].toUpperCase() + p.slice(1)).join('');
    return this.safeDartName(`${method}${name}`);
  }

  private safeDartName(name: string): string {
    const reserved = new Set([
      'abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch', 'class', 'const',
      'continue', 'covariant', 'default', 'deferred', 'do', 'dynamic', 'else', 'enum', 'export',
      'extends', 'extension', 'external', 'factory', 'false', 'final', 'finally', 'for', 'Function',
      'get', 'hide', 'if', 'implements', 'import', 'in', 'interface', 'is', 'late', 'library', 'mixin',
      'new', 'null', 'on', 'operator', 'part', 'required', 'rethrow', 'return', 'set', 'show', 'static',
      'super', 'switch', 'sync', 'this', 'throw', 'true', 'try', 'typedef', 'var', 'void', 'while',
      'with', 'yield',
    ]);
    let safe = name.replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(safe)) safe = '_' + safe;
    if (reserved.has(safe)) safe += '_';
    return safe;
  }
}

interface Operation {
  path: string;
  method: string;
  operation: any;
}

interface Parameter {
  name: string;
  in: string;
  required: boolean;
  schema: any;
}
