/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/

/**
 * Generates a Go client from an OpenAPI document.
 *
 * Output uses the standard `net/http` package, `encoding/json`, and simple
 * request helpers. Component schemas become Go structs with `json` tags.
 */
export class GoClientGenerator {
  private baseUrl: string;
  private schemas: Record<string, any> = {};
  private generatedTypes = new Set<string>();

  constructor(baseUrl = 'http://localhost:3000') {
    this.baseUrl = baseUrl.replace(/\/$/, '');
  }

  generate(spec: any): string {
    this.schemas = spec.components?.schemas || {};
    this.generatedTypes.clear();

    const lines: string[] = [];
    lines.push('// Auto-generated by specscribe — do not edit manually');
    lines.push('// Re-generate: npx specscribe generate src --format go-client');
    lines.push('package generated');
    lines.push('');
    lines.push('import (');
    lines.push('    "bytes"');
    lines.push('    "encoding/json"');
    lines.push('    "fmt"');
    lines.push('    "net/http"');
    lines.push('    "strings"');
    lines.push(')');
    lines.push('');

    const schemaNames = Object.keys(this.schemas).sort();
    if (schemaNames.length > 0) {
      lines.push('// ─── Types ───────────────────────────────────────────────────────────');
      for (const name of schemaNames) {
        lines.push(this.structForSchema(name, this.schemas[name]));
      }
      lines.push('');
    }

    lines.push('// ─── Client ──────────────────────────────────────────────────────────');
    lines.push('type Client struct {');
    lines.push('    BaseURL string');
    lines.push('    HTTP    *http.Client');
    lines.push('}');
    lines.push('');
    lines.push('func NewClient() *Client {');
    lines.push(`    return &Client{BaseURL: "${this.baseUrl}", HTTP: &http.Client{}}`);
    lines.push('}');
    lines.push('');

    const operations = this.collectOperations(spec.paths || {});
    for (const op of operations) {
      lines.push(this.methodForOperation(op));
      lines.push('');
    }

    // Helpers
    lines.push('func buildPath(baseURL, path string) string {')
    lines.push('    if strings.HasSuffix(baseURL, "/") && strings.HasPrefix(path, "/") {')
    lines.push('        return baseURL + path[1:]')
    lines.push('    }')
    lines.push('    return baseURL + path')
    lines.push('}')

    return lines.join('\n') + '\n';
  }

  private structForSchema(name: string, schema: any, visited = new Set<string>()): string {
    if (this.generatedTypes.has(name)) return '';
    this.generatedTypes.add(name);

    if (visited.has(name)) {
      return `// ${name} omitted due to circular reference`;
    }
    visited.add(name);

    const lines: string[] = [];
    const properties = schema.properties || {};
    const required = new Set(schema.required || []);

    // Emit nested object types first
    for (const propSchema of Object.values(properties) as any[]) {
      if (propSchema.type === 'object' && propSchema.properties && propSchema.title && !this.generatedTypes.has(propSchema.title)) {
        lines.push(this.structForSchema(propSchema.title, propSchema, visited));
      }
    }

    lines.push(`type ${this.safeGoTypeName(name)} struct {`);
    const propKeys = Object.keys(properties);
    if (propKeys.length === 0) {
      lines.push('    // no fields');
    } else {
      for (const propName of propKeys) {
        const propSchema = properties[propName];
        const goType = this.schemaToGoType(propSchema, !required.has(propName));
        const tag = `json:"${propName},omitempty"`;
        lines.push(`    ${this.goFieldName(propName)} ${goType} \`${tag}\``);
      }
    }
    lines.push('}');

    visited.delete(name);
    return lines.filter(Boolean).join('\n');
  }

  private collectOperations(paths: Record<string, Record<string, any>>): Operation[] {
    const operations: Operation[] = [];
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (typeof operation !== 'object' || !operation) continue;
        operations.push({ path, method: method.toLowerCase(), operation });
      }
    }
    return operations;
  }

  private methodForOperation(op: Operation): string {
    const { path, method, operation } = op;
    const funcName = this.methodName(operation.operationId, method, path);
    const params = this.extractParameters(operation);
    const pathParams = params.filter(p => p.in === 'path');
    const queryParams = params.filter(p => p.in === 'query');
    const bodyParam = operation.requestBody?.content?.['application/json'];

    const sigParts: string[] = ['c *Client'];
    for (const p of pathParams) {
      sigParts.push(`${this.safeGoName(p.name)} string`);
    }
    if (bodyParam?.schema) {
      sigParts.push(`body ${this.schemaToGoType(bodyParam.schema, false)}`);
    }

    const lines: string[] = [];
    lines.push(`func ${funcName}(${sigParts.join(', ')}) (*http.Response, error) {`);

    let urlPath = path;
    for (const p of pathParams) {
      urlPath = urlPath.replace(`{${p.name}}`, `%s`);
    }
    const fmtArgs = pathParams.map(p => this.safeGoName(p.name)).join(', ');
    const urlLine = fmtArgs ? `    path := fmt.Sprintf("${urlPath}", ${fmtArgs})` : `    path := "${urlPath}"`;
    lines.push(urlLine);
    lines.push('    url := buildPath(c.BaseURL, path)');

    if (bodyParam?.schema) {
      lines.push('    payload, err := json.Marshal(body)');
      lines.push('    if err != nil {');
      lines.push('        return nil, err');
      lines.push('    }');
      lines.push(`    req, err := http.NewRequest("${method.toUpperCase()}", url, bytes.NewBuffer(payload))`);
    } else {
      lines.push(`    req, err := http.NewRequest("${method.toUpperCase()}", url, nil)`);
    }
    lines.push('    if err != nil {');
    lines.push('        return nil, err');
    lines.push('    }');

    if (bodyParam?.schema) {
      lines.push('    req.Header.Set("Content-Type", "application/json")');
    }

    if (queryParams.length > 0) {
      lines.push('    q := req.URL.Query()');
      for (const q of queryParams) {
        lines.push(`    q.Add("${q.name}", fmt.Sprintf("%v", ${this.safeGoName(q.name)}))`);
      }
      lines.push('    req.URL.RawQuery = q.Encode()');
    }

    lines.push('    return c.HTTP.Do(req)');
    lines.push('}');

    return lines.join('\n');
  }

  private extractParameters(operation: any): Parameter[] {
    return (operation.parameters || []).map((p: any) => ({
      name: p.name,
      in: p.in,
      required: p.required === true,
      schema: p.schema || {},
    }));
  }

  private schemaToGoType(schema: any, optional: boolean): string {
    if (!schema) return 'interface{}';
    if (schema.$ref) {
      const name = schema.$ref.split('/').pop();
      return optional ? `*${this.safeGoTypeName(name)}` : this.safeGoTypeName(name);
    }
    if (Array.isArray(schema.type)) {
      return 'interface{}';
    }
    if (schema.type === 'array') {
      const item = this.schemaToGoType(schema.items, false);
      return `[]${item}`;
    }
    if (schema.enum) return 'string';
    let type: string;
    switch (schema.type) {
      case 'string':
        type = schema.format === 'date-time' ? 'time.Time' : 'string';
        break;
      case 'integer': type = 'int'; break;
      case 'number': type = 'float64'; break;
      case 'boolean': type = 'bool'; break;
      case 'object':
        type = schema.title ? this.safeGoTypeName(schema.title) : 'map[string]interface{}';
        break;
      default:
        type = 'interface{}';
    }
    return optional ? `*${type}` : type;
  }

  private methodName(operationId: string | undefined, method: string, path: string): string {
    const raw = operationId
      ? this.safeGoName(operationId)
      : this.safeGoName(`${method}${this.pathToName(path)}`);
    return this.capitalize(raw);
  }

  private pathToName(path: string): string {
    const parts = path.replace(/[{}]/g, '').split('/').filter(Boolean);
    return parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('') || 'Root';
  }

  private capitalize(name: string): string {
    return name.charAt(0).toUpperCase() + name.slice(1);
  }

  private safeGoTypeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }

  private safeGoName(name: string): string {
    const safe = name.replace(/[^a-zA-Z0-9_]/g, '_');
    return safe.replace(/^[0-9]/, '_$&');
  }

  private goFieldName(name: string): string {
    return this.safeGoName(name).replace(/_(.)/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, c => c.toUpperCase());
  }
}

interface Operation {
  path: string;
  method: string;
  operation: any;
}

interface Parameter {
  name: string;
  in: string;
  required: boolean;
  schema: any;
}
