/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/

/**
 * Generates a dependency-light Python client from an OpenAPI document.
 *
 * Output uses `dataclasses`, `requests`, and standard-library `json`. Each
 * component schema becomes a dataclass, and each path/operation becomes a method
 * on `ApiClient`.
 */
export class PythonClientGenerator {
  private schemas: Record<string, any> = {};
  private generatedTypes = new Set<string>();
  private baseUrl: string;

  constructor(baseUrl = 'http://localhost:3000') {
    this.baseUrl = baseUrl.replace(/\/$/, '');
  }

  generate(spec: any): string {
    this.schemas = spec.components?.schemas || {};
    this.generatedTypes.clear();

    const lines: string[] = [];
    lines.push('# Auto-generated by specscribe — do not edit manually');
    lines.push('# Re-generate: npx specscribe generate src --format python-client');
    lines.push('from dataclasses import dataclass, field');
    lines.push('from typing import Any, Dict, List, Optional, Union');
    lines.push('import json');
    lines.push('import requests');
    lines.push('');

    const schemaNames = Object.keys(this.schemas).sort();
    if (schemaNames.length > 0) {
      lines.push('# ─── Types ───────────────────────────────────────────────────────────');
      for (const name of schemaNames) {
        lines.push(this.dataclassForSchema(name, this.schemas[name]));
      }
      lines.push('');
    }

    lines.push('# ─── Client ──────────────────────────────────────────────────────────');
    lines.push('class ApiClient:');
    lines.push(`    def __init__(self, base_url: str = "${this.baseUrl}"):`);
    lines.push('        self.base_url = base_url.rstrip("/")');
    lines.push('');

    const operations = this.collectOperations(spec.paths || {});
    for (const op of operations) {
      lines.push(this.methodForOperation(op).map(l => `    ${l}`).join('\n'));
      lines.push('');
    }

    return lines.join('\n') + '\n';
  }

  private dataclassForSchema(name: string, schema: any, visited = new Set<string>()): string {
    if (this.generatedTypes.has(name)) return '';
    this.generatedTypes.add(name);

    if (visited.has(name)) {
      return `@dataclass\nclass ${name}:\n    pass  # circular reference`;
    }
    visited.add(name);

    const lines: string[] = [];
    const properties = schema.properties || {};
    const required = new Set(schema.required || []);

    // Emit nested object schemas as inline dataclasses first.
    for (const [_propName, propSchema] of Object.entries(properties)) {
      const child = propSchema as any;
      if (child.type === 'object' && child.properties && child.title && !this.generatedTypes.has(child.title)) {
        lines.push(this.dataclassForSchema(child.title, child, visited));
      }
    }

    lines.push('@dataclass');
    lines.push(`class ${name}:`);
    const propKeys = Object.keys(properties);
    if (propKeys.length === 0) {
      lines.push('    pass');
    } else {
      for (const propName of propKeys) {
        const propSchema = properties[propName];
        const optional = !required.has(propName);
        const pyType = this.schemaToPythonType(propSchema, optional);
        const defaultValue = optional ? ' = None' : '';
        lines.push(`    ${this.safePythonName(propName)}: ${pyType}${defaultValue}`);
      }
    }

    visited.delete(name);
    return lines.filter(Boolean).join('\n');
  }

  private collectOperations(paths: Record<string, Record<string, any>>): Operation[] {
    const operations: Operation[] = [];
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (typeof operation !== 'object' || !operation) continue;
        operations.push({
          path,
          method: method.toLowerCase(),
          operation,
        });
      }
    }
    return operations;
  }

  private methodForOperation(op: Operation): string[] {
    const { path, method, operation } = op;
    const methodName = this.methodName(operation.operationId, method, path);
    const params = this.extractParameters(operation);

    const sigParts: string[] = ['self'];
    for (const param of params) {
      sigParts.push(`${this.safePythonName(param.name)}: ${this.schemaToPythonType(param.schema, !param.required)}`);
    }
    const bodyParam = operation.requestBody?.content?.['application/json'];
    if (bodyParam?.schema) {
      const bodyType = this.schemaToPythonType(bodyParam.schema, false);
      sigParts.push(`body: ${bodyType}`);
    }
    sigParts.push('**kwargs: Any');

    const lines: string[] = [];
    lines.push(`def ${methodName}(${sigParts.join(', ')}) -> Any:`);
    const summary = operation.summary || `${method.toUpperCase()} ${path}`;
    lines.push(`    """${summary}"""`);

    const url = this.buildUrl(path, params.filter(p => p.in === 'path'));
    lines.push(`    url = ${url}`);

    const queryParams = params.filter(p => p.in === 'query');
    if (queryParams.length > 0) {
      const queryDict = queryParams.map(p => `"${p.name}": ${this.safePythonName(p.name)}`).join(', ');
      lines.push(`    params = {${queryDict}}`);
      lines.push('    kwargs.setdefault("params", {})');
      lines.push('    kwargs["params"].update({k: v for k, v in params.items() if v is not None})');
    }

    if (bodyParam?.schema) {
      lines.push('    response = requests.request(method, url, json=body.__dict__ if hasattr(body, "__dataclass_fields__") else body, **kwargs)');
    } else {
      lines.push('    response = requests.request(method, url, **kwargs)');
    }
    lines.push('    response.raise_for_status()');
    lines.push('    try:');
    lines.push('        return response.json()');
    lines.push('    except json.JSONDecodeError:');
    lines.push('        return response.text');

    return lines;
  }

  private extractParameters(operation: any): Parameter[] {
    const params: Parameter[] = [];
    for (const param of operation.parameters || []) {
      params.push({
        name: param.name,
        in: param.in,
        required: param.required === true,
        schema: param.schema || {},
      });
    }
    return params;
  }

  private buildUrl(path: string, pathParams: Parameter[]): string {
    let url = `f"${this.baseUrl}${path}"`;
    for (const param of pathParams) {
      url = url.replace(`{${param.name}}`, `{${this.safePythonName(param.name)}}`);
    }
    return url;
  }

  private schemaToPythonType(schema: any, optional: boolean): string {
    if (!schema) return 'Any';
    if (schema.$ref) {
      const name = schema.$ref.split('/').pop();
      return this.optionalType(name, optional);
    }
    if (Array.isArray(schema.type)) {
      const types = schema.type.map((t: string) => t === 'null' ? 'None' : this.basicType(t, schema));
      return this.optionalType(`Union[${types.join(', ')}]`, optional);
    }
    if (schema.type === 'array') {
      const item = this.schemaToPythonType(schema.items, false);
      return this.optionalType(`List[${item}]`, optional);
    }
    if (schema.enum) {
      return this.optionalType('str', optional);
    }
    const basic = this.basicType(schema.type, schema);
    return this.optionalType(basic, optional);
  }

  private basicType(type: string, schema: any): string {
    switch (type) {
      case 'string':
        if (schema.format === 'date-time') return 'str';
        return 'str';
      case 'integer':
        return 'int';
      case 'number':
        return 'float';
      case 'boolean':
        return 'bool';
      case 'object':
        return schema.title ? schema.title : 'Dict[str, Any]';
      default:
        return 'Any';
    }
  }

  private optionalType(type: string, optional: boolean): string {
    return optional ? `Optional[${type}]` : type;
  }

  private methodName(operationId: string | undefined, method: string, path: string): string {
    if (operationId) return this.safePythonName(operationId);
    const parts = path.replace(/[{}]/g, '').split('/').filter(Boolean);
    const name = parts.length === 0 ? 'root' : parts.join('_');
    return this.safePythonName(`${method}_${name}`);
  }

  private safePythonName(name: string): string {
    const reserved = new Set([
      'class', 'def', 'if', 'else', 'elif', 'for', 'while', 'try', 'except', 'finally',
      'with', 'as', 'return', 'yield', 'pass', 'break', 'continue', 'raise', 'import',
      'from', 'in', 'is', 'not', 'and', 'or', 'lambda', 'True', 'False', 'None',
    ]);
    let safe = name.replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(safe)) safe = '_' + safe;
    if (reserved.has(safe)) safe += '_';
    return safe;
  }
}

interface Operation {
  path: string;
  method: string;
  operation: any;
}

interface Parameter {
  name: string;
  in: string;
  required: boolean;
  schema: any;
}
