/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/

/**
 * Generates React Query (TanStack Query) hooks from an OpenAPI document.
 *
 * Each GET operation becomes a `useQuery` hook; mutations become `useMutation`.
 * The output is a TypeScript file with one hook per operation, grouped by tag.
 */
export class ReactQueryHooksGenerator {
  private baseUrl: string;

  constructor(baseUrl = 'http://localhost:3000') {
    this.baseUrl = baseUrl.replace(/\/$/, '');
  }

  generate(spec: any): string {
    const lines: string[] = [];
    lines.push('// Auto-generated by specscribe — do not edit manually');
    lines.push('// Re-generate: npx specscribe generate src --format react-query');
    lines.push("import { useQuery, useMutation, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';");
    lines.push('');
    lines.push(`const BASE_URL = '${this.baseUrl}';`);
    lines.push('');

    const operations = this.collectOperations(spec.paths || {});
    for (const op of operations) {
      lines.push(...this.hookForOperation(op));
      lines.push('');
    }

    return lines.join('\n') + '\n';
  }

  private collectOperations(paths: Record<string, Record<string, any>>): Operation[] {
    const operations: Operation[] = [];
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (typeof operation !== 'object' || !operation) continue;
        operations.push({ path, method: method.toLowerCase(), operation });
      }
    }
    return operations;
  }

  private hookForOperation(op: Operation): string[] {
    const { path, method, operation } = op;
    const hookName = this.hookName(operation.operationId, method, path);
    const fnName = this.fetcherName(operation.operationId, method, path);
    const url = this.buildUrl(path);
    const httpMethod = method.toUpperCase();
    const isQuery = method === 'get';

    const lines: string[] = [];
    lines.push(`async function ${fnName}(body?: any, options?: RequestInit): Promise<any> {`);
    lines.push(`  const response = await fetch(BASE_URL + \`${url}\`, {`);
    lines.push(`    method: '${httpMethod}',`);
    lines.push('    ...options,');
    lines.push('    ...(body ? { body: JSON.stringify(body), headers: { "Content-Type": "application/json", ...options?.headers } } : {}),');
    lines.push('  });');
    lines.push('  if (!response.ok) throw new Error(`Request failed: ${response.status}`);');
    lines.push('  return response.json();');
    lines.push('}');
    lines.push('');

    if (isQuery) {
      lines.push(`export function ${hookName}(options?: UseQueryOptions<any, Error, any, [string]>) {`);
      lines.push(`  return useQuery({ queryKey: ['${hookName}'], queryFn: () => ${fnName}(), ...options });`);
      lines.push('}');
    } else {
      lines.push(`export function ${hookName}(options?: UseMutationOptions<any, Error, any>) {`);
      lines.push(`  return useMutation({ mutationFn: ${fnName}, ...options });`);
      lines.push('}');
    }

    return lines;
  }

  private buildUrl(path: string): string {
    return path.replace(/{([^}]+)}/g, '${encodeURIComponent(String($1))}');
  }

  private hookName(operationId: string | undefined, method: string, path: string): string {
    const base = operationId ? this.capitalize(operationId) : this.capitalize(method) + this.pathToName(path);
    return `use${base}`;
  }

  private fetcherName(operationId: string | undefined, method: string, path: string): string {
    const base = operationId ? operationId : `${method}${this.pathToName(path)}`;
    return `fetch${this.capitalize(base)}`;
  }

  private pathToName(path: string): string {
    return path
      .replace(/[{}]/g, '')
      .split('/')
      .filter(Boolean)
      .map(s => s.charAt(0).toUpperCase() + s.slice(1))
      .join('');
  }

  private capitalize(name: string): string {
    return name.charAt(0).toUpperCase() + name.slice(1);
  }
}

interface Operation {
  path: string;
  method: string;
  operation: any;
}
