/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/

/**
 * Generates an RTK Query API slice from an OpenAPI document.
 *
 * Each operation becomes an endpoint builder entry. GETs default to `query`,
 * everything else defaults to `mutation`.
 */
export class RtkQueryGenerator {
  private baseUrl: string;

  constructor(baseUrl = 'http://localhost:3000') {
    this.baseUrl = baseUrl.replace(/\/$/, '');
  }

  generate(spec: any): string {
    const lines: string[] = [];
    lines.push('// Auto-generated by specscribe — do not edit manually');
    lines.push('// Re-generate: npx specscribe generate src --format rtk-query');
    lines.push("import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';");
    lines.push('');
    lines.push(`const baseQuery = fetchBaseQuery({ baseUrl: '${this.baseUrl}' });`);
    lines.push('');
    lines.push('export const api = createApi({');
    lines.push('  baseQuery,');
    lines.push("  reducerPath: 'specscribeApi',");
    lines.push('  endpoints: (builder) => ({');

    const operations = this.collectOperations(spec.paths || {});
    for (const op of operations) {
      lines.push(...this.endpointForOperation(op).map(l => `    ${l}`));
    }
    lines.push('  }),');
    lines.push('});');
    lines.push('');
    lines.push('export const { ' + operations.map(op => this.endpointName(op.operation.operationId, op.method, op.path)).join(', ') + ' } = api;');

    return lines.join('\n') + '\n';
  }

  private collectOperations(paths: Record<string, Record<string, any>>): Operation[] {
    const operations: Operation[] = [];
    for (const [path, methods] of Object.entries(paths)) {
      for (const [method, operation] of Object.entries(methods)) {
        if (typeof operation !== 'object' || !operation) continue;
        operations.push({ path, method: method.toLowerCase(), operation });
      }
    }
    return operations;
  }

  private endpointForOperation(op: Operation): string[] {
    const { path, method, operation } = op;
    const name = this.endpointName(operation.operationId, method, path);
    const isQuery = method === 'get';
    const builder = isQuery ? 'query' : 'mutation';
    const type = isQuery ? 'void' : 'any';
    const bodyArg = isQuery ? '' : ', body: any';

    const lines: string[] = [];
    lines.push(`${name}: builder.${builder}<any, ${type}>({`);
    if (isQuery) {
      lines.push(`    query: () => \`${this.buildUrl(path)}\`,`);
    } else {
      lines.push(`    query: (body${bodyArg ? '' : ''}) => ({`);
      lines.push(`      url: \`${this.buildUrl(path)}\`,`);
      lines.push(`      method: '${method.toUpperCase()}',`);
      lines.push('      body,');
      lines.push('    }),');
    }
    lines.push('  }),');
    return lines;
  }

  private buildUrl(path: string): string {
    return path.replace(/{([^}]+)}/g, '${$1}');
  }

  private endpointName(operationId: string | undefined, method: string, path: string): string {
    if (operationId) return this.safeName(operationId);
    const parts = path.replace(/[{}]/g, '').split('/').filter(Boolean);
    const suffix = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
    return this.safeName(`${method}${suffix || 'Root'}`);
  }

  private safeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&');
  }
}

interface Operation {
  path: string;
  method: string;
  operation: any;
}
