/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/
import { ControllerInfo, MethodInfo, ParameterInfo } from '../scanner/ScannerService';
import { AnalyzedType, PropertyInfo } from '../utils/DtoAnalyzer';
import { FileFieldInfo } from '../utils/FileUploadExtractor';
import { sanitizeTypeName } from '../utils/SchemaName';

/**
 * Read once, from the package itself. A literal default here goes stale at the next
 * release and stamps the wrong version into the user's generated file, where it looks
 * authoritative and is never questioned.
 */
function packageVersion(): string {
  try {
    return require('../../package.json').version as string;
  } catch {
    return '0.0.0';
  }
}

/**
 * Generates a fully-typed TypeScript HTTP client from scanned NestJS controllers.
 * The output file uses native fetch, has zero runtime dependencies, and stays in sync
 * with your controllers by re-running the CLI.
 */
export class TypedClientGenerator {
  constructor(
    private readonly baseUrl: string = 'http://localhost:3000',
    private readonly globalPrefix: string = '',
  ) {}

  generate(controllers: ControllerInfo[], version = packageVersion()): string {
    const lines: string[] = [];

    lines.push(`// Auto-generated by specscribe v${version} — do not edit manually`);
    lines.push(`// Re-generate: npx specscribe generate src --format client`);
    lines.push('');

    // Emit real interfaces reconstructed from the scanned DTO shapes, so the
    // generated client is actually type safe. Emitting `{ [key: string]: unknown }`
    // stubs would compile but silently accept any property.
    this.assignedNames.clear();
    this.fingerprintByName.clear();
    this.firstNameByBase.clear();

    const dtoShapes = this.collectDtoShapes(controllers);
    const enums = this.collectEnums(controllers);

    if (enums.size > 0) {
      lines.push('// ─── Enums ───────────────────────────────────────────────────────────');
      for (const [name, values] of Array.from(enums).sort((a, b) => a[0].localeCompare(b[0]))) {
        const union = values.map(v => `'${v}'`).join(' | ');
        lines.push(`export type ${name} = ${union};`);
      }
      lines.push('');
    }

    if (dtoShapes.size > 0) {
      lines.push('// ─── Types ───────────────────────────────────────────────────────────');
      const sorted = Array.from(dtoShapes.keys()).sort((a, b) => a.localeCompare(b));
      for (const name of sorted) {
        const properties = dtoShapes.get(name)!;
        if (properties.length === 0) {
          // Shape could not be resolved from the AST (e.g. an external type).
          lines.push(`export type ${name} = unknown;`);
          continue;
        }

        lines.push(`export interface ${name} {`);
        for (const prop of properties) {
          if (prop.description) {
            lines.push(`  /** ${prop.description} */`);
          }
          const optional = prop.type.isOptional ? '?' : '';
          lines.push(`  ${prop.name}${optional}: ${this.toTsType(prop.type)};`);
        }
        lines.push('}');
        lines.push('');
      }
    }

    // One class per controller
    for (const controller of controllers) {
      if (controller.methods.length === 0) continue;
      lines.push(...this.buildControllerClass(controller));
      lines.push('');
    }

    // Convenience factory that aggregates all clients
    lines.push(...this.buildAggregateClient(controllers));

    return lines.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private buildControllerClass(controller: ControllerInfo): string[] {
    const className = this.toClassName(controller.name) + 'Client';
    const lines: string[] = [];

    lines.push(`export class ${className} {`);
    lines.push(`  constructor(private readonly baseUrl: string) {}`);
    lines.push('');

    for (const method of controller.methods) {
      lines.push(...this.buildMethod(controller.path, method).map(l => `  ${l}`));
      lines.push('');
    }

    lines.push('}');
    return lines;
  }

  private buildMethod(controllerPath: string, method: MethodInfo): string[] {
    const lines: string[] = [];

    const pathParams = method.parameters.filter(p => p.parameterLocation === 'path' || p.decorator === 'Param');
    const queryParams = method.parameters.filter(p => p.parameterLocation === 'query' || p.decorator === 'Query');
    const bodyParam = method.parameters.find(p => p.parameterLocation === 'body' || p.decorator === 'Body');

    const fileFields = method.fileFields ?? [];
    const isUpload = fileFields.length > 0;

    const returnTs = this.toTsType(method.returnType);
    const fnParams = this.buildFnParams(pathParams, queryParams, bodyParam, fileFields);
    const fullRoute = this.joinPath(this.globalPrefix, controllerPath, method.route);

    lines.push(`async ${method.name}(${fnParams}): Promise<${returnTs}> {`);

    // Build URL
    const urlExpr = this.buildUrlExpr(fullRoute, pathParams);
    if (queryParams.length > 0) {
      lines.push(`  const _url = new URL(\`\${this.baseUrl}${urlExpr}\`);`);
      for (const qp of queryParams) {
        const isOptional = qp.type.isOptional;
        if (isOptional) {
          lines.push(`  if (${qp.name} !== undefined) _url.searchParams.set('${qp.name}', String(${qp.name}));`);
        } else {
          lines.push(`  _url.searchParams.set('${qp.name}', String(${qp.name}));`);
        }
      }
    }

    const urlArg = queryParams.length > 0 ? '_url.toString()' : `\`\${this.baseUrl}${urlExpr}\``;

    // Build fetch call
    const httpMethod = method.httpMethod.toUpperCase();
    if (isUpload) {
      // A multipart endpoint rejects a JSON body, so the request must be built
      // as FormData. The Content-Type header is deliberately omitted: the
      // browser adds it together with the required multipart boundary.
      lines.push(`  const _form = new FormData();`);

      for (const field of fileFields) {
        const name = this.toIdentifier(field.name);
        if (field.multiple) {
          lines.push(`  for (const _f of ${name}) _form.append('${field.name}', _f);`);
        } else {
          lines.push(`  _form.append('${field.name}', ${name});`);
        }
      }

      if (bodyParam) {
        lines.push(`  for (const [_k, _v] of Object.entries(${bodyParam.name} ?? {})) {`);
        lines.push(`    if (_v !== undefined) _form.append(_k, String(_v));`);
        lines.push(`  }`);
      }

      lines.push(`  const _res = await fetch(${urlArg}, {`);
      lines.push(`    method: '${httpMethod}',`);
      lines.push(`    body: _form,`);
      lines.push(`  });`);
    } else if (bodyParam) {
      lines.push(`  const _res = await fetch(${urlArg}, {`);
      lines.push(`    method: '${httpMethod}',`);
      lines.push(`    headers: { 'Content-Type': 'application/json' },`);
      lines.push(`    body: JSON.stringify(${bodyParam.name}),`);
      lines.push(`  });`);
    } else {
      if (httpMethod === 'GET') {
        lines.push(`  const _res = await fetch(${urlArg});`);
      } else {
        lines.push(`  const _res = await fetch(${urlArg}, { method: '${httpMethod}' });`);
      }
    }

    // Return handling
    if (returnTs === 'void') {
      lines.push(`  if (!_res.ok) throw new Error(\`${method.name} failed: \${_res.status}\`);`);
    } else {
      lines.push(`  if (!_res.ok) throw new Error(\`${method.name} failed: \${_res.status}\`);`);
      lines.push(`  return _res.json() as Promise<${returnTs}>;`);
    }

    lines.push('}');
    return lines;
  }

  /** Turns a form field name into a valid TypeScript parameter name. */
  private toIdentifier(fieldName: string): string {
    const cleaned = fieldName.replace(/[^A-Za-z0-9_$]/g, '_');
    return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
  }

  private buildFnParams(
    pathParams: ParameterInfo[],
    queryParams: ParameterInfo[],
    bodyParam: ParameterInfo | undefined,
    fileFields: FileFieldInfo[] = [],
  ): string {
    const parts: string[] = [];

    for (const p of pathParams) {
      parts.push(`${p.name}: ${this.toTsType(p.type)}`);
    }
    // Files come before the optional metadata so the signature stays callable.
    for (const field of fileFields) {
      parts.push(`${this.toIdentifier(field.name)}: ${field.multiple ? 'File[]' : 'File'}`);
    }
    for (const p of queryParams) {
      const opt = p.type.isOptional ? '?' : '';
      parts.push(`${p.name}${opt}: ${this.toTsType(p.type)}`);
    }
    if (bodyParam) {
      const opt = bodyParam.type.isOptional ? '?' : '';
      parts.push(`${bodyParam.name}${opt}: ${this.toTsType(bodyParam.type)}`);
    }

    return parts.join(', ');
  }

  private buildUrlExpr(route: string, pathParams: ParameterInfo[]): string {
    // Replace :param or {param} with ${param} template literal syntax.
    // IMPORTANT: use a single combined regex so that the second pattern never
    // re-matches a ${param} fragment produced by the first pattern.
    let result = '/' + route.replace(/^\/+/, '').replace(/\/*$/, '');
    for (const p of pathParams) {
      const pattern = new RegExp(`:${p.name}|\\{${p.name}\\}`, 'g');
      // Use string concatenation for the replacement to avoid the special
      // meaning that `$` has inside String.prototype.replace replacement strings.
      result = result.replace(pattern, '${' + p.name + '}');
    }
    return result;
  }

  private buildAggregateClient(controllers: ControllerInfo[]): string[] {
    const valid = controllers.filter(c => c.methods.length > 0);
    if (valid.length === 0) return [];

    const lines: string[] = [];
    lines.push('// ─── Aggregate client ───────────────────────────────────────────────────────');
    lines.push('export class ApiClient {');
    for (const c of valid) {
      const propName = this.toCamelCase(c.name.replace(/Controller$/i, ''));
      const className = this.toClassName(c.name) + 'Client';
      lines.push(`  readonly ${propName}: ${className};`);
    }
    lines.push('');
    lines.push('  constructor(baseUrl: string) {');
    for (const c of valid) {
      const propName = this.toCamelCase(c.name.replace(/Controller$/i, ''));
      const className = this.toClassName(c.name) + 'Client';
      lines.push(`    this.${propName} = new ${className}(baseUrl);`);
    }
    lines.push('  }');
    lines.push('}');
    return lines;
  }

  // ---------------------------------------------------------------------------
  // Type helpers
  // ---------------------------------------------------------------------------

  /**
   * Maps `sanitizedBase|shapeFingerprint` to the emitted interface name, so
   * two DTOs that share a class name but not a shape get distinct interfaces
   * instead of the richer one silently winning.
   */
  private readonly assignedNames = new Map<string, string>();
  private readonly fingerprintByName = new Map<string, string>();
  /** First name assigned per base, the fallback for cycle-truncated references. */
  private readonly firstNameByBase = new Map<string, string>();

  /**
   * Resolves the interface name a type is emitted (and referenced) under.
   * Returns `null` for primitives and anonymous shapes, which keep their raw
   * text.
   */
  private resolveTypeName(t: AnalyzedType): string | null {
    const base = sanitizeTypeName(t.type.replace(/\[\]$/, ''));
    if (!base || !this.isNamedType(base)) {
      return null;
    }

    if (!t.properties || t.properties.length === 0) {
      // Cycle-truncated or external reference: reuse whichever interface was
      // assigned for this name first.
      return this.firstNameByBase.get(base) ?? base;
    }

    const fingerprint = JSON.stringify(t.properties);
    const key = `${base}|${fingerprint}`;

    let assigned = this.assignedNames.get(key);
    if (!assigned) {
      assigned = base;
      let suffix = 2;
      while (this.fingerprintByName.has(assigned) && this.fingerprintByName.get(assigned) !== fingerprint) {
        assigned = `${base}${suffix++}`;
      }
      this.assignedNames.set(key, assigned);
      this.fingerprintByName.set(assigned, fingerprint);
      if (!this.firstNameByBase.has(base)) {
        this.firstNameByBase.set(base, assigned);
      }
    }

    return assigned;
  }

  /**
   * Walks every scanned type and records the resolved property list for each
   * named object type, so real interfaces can be emitted.
   */
  private collectDtoShapes(controllers: ControllerInfo[]): Map<string, PropertyInfo[]> {
    const shapes = new Map<string, PropertyInfo[]>();
    const unresolvedBases = new Set<string>();

    const visit = (t: AnalyzedType) => {
      const base = sanitizeTypeName(t.type.replace(/\[\]$/, ''));

      if (base && this.isNamedType(base) && !t.enumValues) {
        if (t.properties && t.properties.length > 0) {
          const assigned = this.resolveTypeName(t)!;
          if (!shapes.has(assigned)) {
            shapes.set(assigned, t.properties);
          }
        } else {
          unresolvedBases.add(base);
        }
      }

      for (const p of t.properties ?? []) {
        visit(p.type);
      }
    };

    for (const c of controllers) {
      for (const m of c.methods) {
        visit(m.returnType);
        for (const p of m.parameters) visit(p.type);
      }
    }

    // Names that never resolved to a shape anywhere (e.g. external types) are
    // still emitted, as `unknown`, so the client compiles.
    for (const base of unresolvedBases) {
      if (!this.firstNameByBase.has(base) && !shapes.has(base)) {
        shapes.set(base, []);
      }
    }

    return shapes;
  }

  /**
   * Collects enum-like types as string literal unions, which is both accurate
   * and dependency free in the generated output.
   */
  private collectEnums(controllers: ControllerInfo[]): Map<string, string[]> {
    const enums = new Map<string, string[]>();
    const seen = new Set<string>();

    const visit = (t: AnalyzedType) => {
      const base = t.type.replace(/\[\]$/, '');

      if (t.enumValues && t.enumValues.length > 0 && this.isNamedType(base)) {
        enums.set(base, t.enumValues);
      }

      if (t.properties && !seen.has(base)) {
        seen.add(base);
        for (const p of t.properties) visit(p.type);
      }
    };

    for (const c of controllers) {
      for (const m of c.methods) {
        visit(m.returnType);
        for (const p of m.parameters) visit(p.type);
      }
    }

    return enums;
  }

  /** True for PascalCase names that map to a declared type, not a primitive. */
  private isNamedType(name: string): boolean {
    const primitives = new Set([
      'string', 'number', 'boolean', 'any', 'void', 'unknown', 'object', 'never',
      'null', 'undefined', 'Date', 'String', 'Number', 'Boolean', 'Object',
    ]);
    return !primitives.has(name) && /^[A-Z][A-Za-z0-9_]*$/.test(name);
  }

  private toTsType(t: AnalyzedType): string {
    const primitiveMap: Record<string, string> = {
      String: 'string', Number: 'number', Boolean: 'boolean',
      Date: 'string', Object: 'unknown',
    };

    let base = primitiveMap[t.type] ?? t.type;
    if (!base || base === '' || base === 'undefined' || base === 'null') base = 'unknown';

    // Named object types are referenced under their assigned interface name,
    // which may differ from the raw text (sanitized generics, deduplicated
    // same-named DTOs).
    if (!t.enumValues) {
      const assigned = this.resolveTypeName(t);
      if (assigned) {
        base = assigned;
      }
    }

    return t.isArray ? `${base}[]` : base;
  }

  // ---------------------------------------------------------------------------
  // String helpers
  // ---------------------------------------------------------------------------

  private toClassName(name: string): string {
    // PascalCase — strip common suffixes first
    return name.charAt(0).toUpperCase() + name.slice(1);
  }

  private toCamelCase(name: string): string {
    return name.charAt(0).toLowerCase() + name.slice(1);
  }

  private joinPath(...parts: string[]): string {
    return parts
      .map(p => p.replace(/^\/+|\/+$/g, ''))
      .filter(Boolean)
      .join('/');
  }
}
