/** SpecScribe | Developed by Mohamed Mustafa | MIT License **/
import { Scenario, ScenarioStep } from './ScenarioRunner';

/**
 * Generates ready-to-run test scenarios from an OpenAPI document.
 *
 * The generator applies the heuristics a developer would: create before read,
 * read before update, delete last; log in first when the API has a login
 * endpoint and thread the captured token through every request; capture ids
 * from create responses and use them for the `/:id` routes; and assert that
 * every response matches its documented schema.
 */

interface OperationEntry {
  path: string;
  method: string;
  operation: any;
  tag: string;
}

/** Follows `#/components/schemas/X` references, one level at a time. */
function deref(schema: any, spec: any, depth = 0): any {
  if (!schema || depth > 10) return schema;
  if (schema.$ref && typeof schema.$ref === 'string') {
    const name = schema.$ref.split('/').pop() as string;
    return deref(spec?.components?.schemas?.[name], spec, depth + 1);
  }
  return schema;
}

const STRING_EXAMPLES: Array<[RegExp, string]> = [
  [/e-?mail/i, 'user@example.com'],
  [/password/i, 'SecurePassword123!'],
  [/phone/i, '+15550100'],
  [/(url|uri|link|website)/i, 'https://example.com'],
  [/(uuid|guid)/i, '00000000-0000-4000-8000-000000000001'],
  [/(date|time|at$)/i, '2026-01-01T00:00:00.000Z'],
  [/name/i, 'Example Name'],
  [/description|bio|summary/i, 'Generated by specscribe'],
];

const FORMAT_EXAMPLES: Record<string, string> = {
  email: 'user@example.com',
  uri: 'https://example.com',
  url: 'https://example.com',
  uuid: '00000000-0000-4000-8000-000000000001',
  'date-time': '2026-01-01T00:00:00.000Z',
  date: '2026-01-01',
};

/** True when a documented example is usable for the declared schema type. */
function exampleMatchesType(example: unknown, type: string | undefined): boolean {
  switch (type) {
    case 'array':
      return Array.isArray(example);
    case 'object':
      return typeof example === 'object' && example !== null && !Array.isArray(example);
    case 'number':
    case 'integer':
      return typeof example === 'number';
    case 'boolean':
      return typeof example === 'boolean';
    case 'string':
      return typeof example === 'string';
    default:
      return true;
  }
}

/**
 * A deterministic example for a JSON schema. Deterministic on purpose:
 * generated scenario files should not churn on every regeneration.
 */
export function exampleFromSchema(schema: any, spec: any, propertyName = '', depth = 0): unknown {
  const resolved = deref(schema, spec);
  if (!resolved || depth > 6) return null;

  // Object schemas with properties are always assembled from the properties:
  // document-level `example` objects are routinely partial (scalars only) and
  // trusting them wholesale produced bodies with missing required fields.
  const hasProperties = resolved.properties && Object.keys(resolved.properties).length > 0;
  if (
    resolved.example !== undefined &&
    !hasProperties &&
    exampleMatchesType(resolved.example, resolved.type)
  ) {
    return resolved.example;
  }
  if (Array.isArray(resolved.enum) && resolved.enum.length) return resolved.enum[0];

  switch (resolved.type) {
    case 'array':
      return [exampleFromSchema(resolved.items, spec, propertyName, depth + 1)];
    case 'object': {
      const out: Record<string, unknown> = {};
      const properties = resolved.properties || {};
      for (const key of Object.keys(properties)) {
        out[key] = exampleFromSchema(properties[key], spec, key, depth + 1);
      }
      return out;
    }
    case 'integer':
    case 'number':
      return typeof resolved.minimum === 'number' ? resolved.minimum : 1;
    case 'boolean':
      return true;
    case 'string': {
      if (resolved.format && FORMAT_EXAMPLES[resolved.format]) {
        return FORMAT_EXAMPLES[resolved.format];
      }
      for (const [pattern, value] of STRING_EXAMPLES) {
        if (pattern.test(propertyName)) return value;
      }
      return 'example';
    }
    default:
      // Untyped schema with properties still describes an object.
      if (resolved.properties) {
        return exampleFromSchema({ ...resolved, type: 'object' }, spec, propertyName, depth);
      }
      return null;
  }
}

/** The first documented 2xx status, as a number. */
function successStatus(operation: any): number {
  const statuses = Object.keys(operation?.responses || {});
  const success = statuses.find(status => status.startsWith('2'));
  return success ? Number(success) : 200;
}

function responseSchema(operation: any, status: number): any {
  return operation?.responses?.[String(status)]?.content?.['application/json']?.schema;
}

function requestSchema(operation: any): any {
  return operation?.requestBody?.content?.['application/json']?.schema;
}

/** Order inside a tag: create → list → read → update → delete. */
function stepRank(entry: OperationEntry): number {
  const hasPathParam = entry.path.includes('{');
  switch (entry.method) {
    case 'post':
      return hasPathParam ? 2 : 0;
    case 'get':
      return hasPathParam ? 3 : 1;
    case 'put':
      return 4;
    case 'patch':
      return 5;
    case 'delete':
      return 6;
    default:
      return 3;
  }
}

const TOKEN_PROPERTIES = ['accessToken', 'access_token', 'token', 'jwt', 'idToken'];

/** Detects a login operation and the token property in its response. */
function findLogin(entries: OperationEntry[], spec: any): { entry: OperationEntry; tokenPath: string } | null {
  for (const entry of entries) {
    if (entry.method !== 'post' || !/log-?in|sign-?in|token/i.test(entry.path)) continue;
    const schema = deref(responseSchema(entry.operation, successStatus(entry.operation)), spec);
    const property = TOKEN_PROPERTIES.find(name => schema?.properties?.[name]);
    if (property) return { entry, tokenPath: `$.${property}` };
  }
  return null;
}

function slug(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'api';
}

function buildStep(
  entry: OperationEntry,
  spec: any,
  context: { idVar?: string; authHeader?: Record<string, string> },
): ScenarioStep {
  const status = successStatus(entry.operation);
  const hasSchema = !!responseSchema(entry.operation, status);

  // Path params: use the captured id when one exists, a literal otherwise.
  const path = entry.path.replace(/\{([^}]+)\}/g, (_match, name) =>
    /id$/i.test(name) && context.idVar ? `{{${context.idVar}}}` : '1',
  );

  const step: ScenarioStep = {
    name: entry.operation.summary || `${entry.method.toUpperCase()} ${entry.path}`,
    request: { method: entry.method.toUpperCase(), path },
    expect: { status, ...(hasSchema ? { matchesSpec: true } : {}) },
  };

  if (context.authHeader && Object.keys(context.authHeader).length) {
    step.request.headers = { ...context.authHeader };
  }

  const bodySchema = requestSchema(entry.operation);
  if (bodySchema) {
    step.request.body = exampleFromSchema(bodySchema, spec);
  }

  return step;
}

/** Generates one scenario per tag, ordered create → read → update → delete. */
export function generateScenarios(spec: any, options: { baseUrl?: string } = {}): Scenario[] {
  const entries: OperationEntry[] = [];
  const paths = spec?.paths || {};

  for (const path of Object.keys(paths)) {
    for (const method of Object.keys(paths[path])) {
      const operation = paths[path][method];
      if (!operation || typeof operation !== 'object') continue;
      entries.push({
        path,
        method: method.toLowerCase(),
        operation,
        tag: (operation.tags && operation.tags[0]) || 'API',
      });
    }
  }
  if (entries.length === 0) return [];

  const login = findLogin(entries, spec);
  const authHeader = login ? { Authorization: 'Bearer {{token}}' } : undefined;

  const loginStep = (): ScenarioStep | null => {
    if (!login) return null;
    const step = buildStep(login.entry, spec, {});
    step.capture = { token: login.tokenPath };
    return step;
  };

  const byTag = new Map<string, OperationEntry[]>();
  for (const entry of entries) {
    const list = byTag.get(entry.tag) || [];
    list.push(entry);
    byTag.set(entry.tag, list);
  }

  const scenarios: Scenario[] = [];
  for (const [tag, tagEntries] of byTag) {
    const ordered = [...tagEntries].sort((a, b) => stepRank(a) - stepRank(b));
    const steps: ScenarioStep[] = [];
    const idVar = `${slug(tag)}Id`;
    let idCaptured = false;

    // Registration must run before the login that depends on the account —
    // on a fresh server the generated credentials exist only after sign-up.
    const preAuth = login
      ? ordered.filter(e => e.method === 'post' && /regist|sign-?up/i.test(e.path))
      : [];
    for (const entry of preAuth) {
      steps.push(buildStep(entry, spec, {}));
    }

    // Every scenario is self-contained: it logs in first when the API has a
    // login endpoint, so scenarios can run individually or filtered.
    const auth = loginStep();
    if (auth) steps.push(auth);

    for (const entry of ordered) {
      if (login && entry === login.entry) continue; // already placed
      if (preAuth.includes(entry)) continue; // already placed before login

      const step = buildStep(entry, spec, {
        idVar: idCaptured ? idVar : undefined,
        authHeader,
      });

      // The first create that answers with an id feeds the /:id routes.
      if (!idCaptured && entry.method === 'post' && !entry.path.includes('{')) {
        const schema = deref(responseSchema(entry.operation, successStatus(entry.operation)), spec);
        if (schema?.properties?.id) {
          step.capture = { [idVar]: '$.id' };
          idCaptured = true;
        }
      }

      steps.push(step);
    }

    if (steps.length === 0 || (auth && steps.length === 1 && tag !== login?.entry.tag)) continue;

    scenarios.push({
      name: `${tag} flow`,
      baseUrl: options.baseUrl || spec?.servers?.[0]?.url || 'http://localhost:3000',
      steps,
    });
  }

  return scenarios;
}

/** File name for a generated scenario: `users.scenario.json`. */
export function scenarioFileName(scenario: Scenario): string {
  return `${slug(scenario.name.replace(/\s+flow$/, ''))}.scenario.json`;
}
